### ISSUE TITLE
Mettre en place Docker Image

### ISSUE THREAD

**Issue by bfoujols** [studoo-app/mock-veliko-api#1]

**Comment by JPechberty** [comment]
Si besoin tu trouveras que j'ai utilisé pour faire l'image avec franken et la github action d'auto build and push sur dockerhub

**_action-build-push.yaml_**
```yaml
name: docker-build-push-to-dockerhub

on:
  push:
    branches:
      - "main"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installation des dépendances composer
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Initiating env
        run: composer edu:init #Commande à mettre à jour pour EduF V2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} #Secret à ajouter dans les secrets du repo
          password: ${{ secrets.DOCKERHUB_PASSWORD }} #Secret à ajouter dans les secrets du repo
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: <username>/<image>:<version>
```
**_Dockerfile_**

```dockerfile
FROM dunglas/frankenphp

ENV SERVER_NAME=localhost
ENV APP_ENV=prod

# ajoutez des extensions supplémentaires ici :
RUN install-php-extensions \
 pdo_mysql \
 gd \
 intl \
 zip \
 opcache

# Installation de composer
RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls && \
       mv composer.phar /usr/local/bin/composer

# Mode prod
#Copy des fichiers de l'application
COPY . /app

```
